
%Compute the intersection of the masks generated by define_DMNandTPN_parcels_L.m and define_DMNandTPN_parcels_R.m.

%% HC
clear; clc;

load('../mask/DMN_TPN_parcels_L.mat');
mask_group_fu_l = mask_group_fu;
mask_group_zheng_l = mask_group_zheng;
mask_group_l = mask_group;

load('../mask/DMN_TPN_parcels_R.mat');
mask_group_fu_r = mask_group_fu;
mask_group_zheng_r = mask_group_zheng;
mask_group_r = mask_group;

mask_group_fu = mask_group_fu_l.*mask_group_fu_r;
mask_group_zheng = mask_group_zheng_l.*mask_group_zheng_r;
mask_group = mask_group_fu*(-1)+mask_group_zheng;

%%%% save mat
save('../mask/DMN_TPN_parcels_combine.mat','mask_group','mask_group_zheng','mask_group_fu');

%% 
nmD = 'HC';
p2u='./Utils/'; addpath(genpath(p2u)); % pth2 cifti utilities
p2prep='../All_Preproc_Data/';  addpath(genpath(p2prep));
load([p2prep 'Prep_Params_' nmD '.mat'],'iXG','nVX');   
nG = length(iXG);
%%%group level
mask = mask_group;
O=nan(nVX,1); 
for nn=1:nG
 O(iXG{nn},1)=mask(1,nn);
end
e=ft_read_cifti('empty.dtseries.nii'); 
e.dtseries=O;   
ft_write_cifti('../mask/DMN_TPN_parcels_combine',e,'parameter','dtseries'); 
% 
% zheng = find(mask_group_zheng~=0);
% lo_sub_zheng = find(zheng>360);
% fu = find(mask_group_fu~=0);
% lo_sub_fu = find(zheng>360);
% 

